### ISSUE TITLE
Compliling Error

### ISSUE THREAD

**Issue by Logan-RX-Alix** [rs-pro0/wallpaper-cava#1]
![error](https://github.com/rs-pro0/wallpaper-cava/assets/172552539/07fef243-d889-401e-84f9-bcaa66f6c878)
Says GradientColor was never constructed (rebuilt it to show error)

![error2](https://github.com/rs-pro0/wallpaper-cava/assets/172552539/262045cd-d15c-458b-9747-bf72056d34bc)
Then this error on running, Could be user error.

**Comment by rs-pro0** [comment]
I will fix the warning, but I think the issue is that you need to have "cava" installed on your system. I will add this to README.

**Comment by rs-pro0** [comment]
Did it help?

**Comment by rs-pro0** [comment]
I hope it works, if not, reopen the issue, please.
