### ISSUE TITLE
Sensitivity option?

### ISSUE THREAD

**Issue by shvedes** [rs-pro0/wallpaper-cava#3]
I think it would be cool to add this to the config

**Comment by rs-pro0** [comment]
I added it in 090089b3392bc329d17c8aa720ed3900f0e82902, check if it is working as expected, please.

**Comment by shvedes** [comment]
Thanks a lot. Just realized that autosense option is more relevant to me. Anyway, i got a question. Is it possible at all to implement all cava config params?

**Comment by rs-pro0** [comment]
Yeah, at least parameters that are supported in raw mode. Just open an issue with a list of the parameters you need, and I'll probably add them.
