### ISSUE TITLE
Multi monitor resolution issues

### ISSUE THREAD

**Issue by juaneth** [rs-pro0/wallpaper-cava#4]
## Description:
I have one 1920x1080 monitor on HDMI-A-1 and one 2560x1440 monitor on DP-1 (my main monitor) but when I run wallpaper-cava on my main monitor by keeping the cursor there (does show) the resolution is always 1920x1080. I've looked through the config provided but can't figure out how to change the resolution OR set a default monitor.

Btw this project is great thank you for your hard work 🙏🏼

## Image:
![image](https://github.com/rs-pro0/wallpaper-cava/assets/68202118/b01b8074-6603-4153-904f-ba63159953cf)

## Neofetch: 
![image](https://github.com/rs-pro0/wallpaper-cava/assets/68202118/5708c266-98d0-432a-b1e7-1ef73d1e5d38)

## Terminal when running:
![image](https://github.com/rs-pro0/wallpaper-cava/assets/68202118/c667acb7-4760-4b68-80da-7e715d25df74)

## Config:
![image](https://github.com/rs-pro0/wallpaper-cava/assets/68202118/8234a5cb-976f-4dc3-ac98-6fd54c07efdd)

**Comment by rs-pro0** [comment]
You can now set preferred monitor in config under general d013378504664f38226046129971c586357c1074

**Comment by rs-pro0** [comment]
I think this should fix your issue, you can reopen it if it didn't help.
