### ISSUE TITLE
--config option? 

### ISSUE THREAD

**Issue by shvedes** [rs-pro0/wallpaper-cava#5]
It would be convenient to run this program from `/usr/local/bin` so that it reads the config from `$HOME/.config`

**Comment by rs-pro0** [comment]
I think I can add option like --config and then you can specify config file
Edit: oh that what you were suggesting, sorry

**Comment by rs-pro0** [comment]
Yeah, I'll implement it

**Comment by rs-pro0** [comment]
I think I added it, please check if it works for you

**Comment by shvedes** [comment]
Sorry for late reply. It works, thanks!!
